import type { Metadata } from "next";
import { Inter, Just_Another_Hand } from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";

const InterFont = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
    weight: ["400", "600", "700", "800", "900"]
});

const JustAnotherHandFont = Just_Another_Hand({
    subsets: ["latin"],
    variable: "--font-handwriting",
    weight: ["400"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`bg-background text-body ${InterFont.variable} ${JustAnotherHandFont.variable} `}>
        {children}
        </body>
        </html>
    );
}
