import type { Metadata } from "next";
import { Inter, Just_Another_Hand } from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import clsx from "clsx";
import dottedBackground from "@/utils/dottedBackground";
import RemoveAnimateAppear from "@/components/layout/RemoveAnimateAppear";

const InterFont = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
    weight: ["400", "600", "700", "800", "900"]
});

const JustAnotherHandFont = Just_Another_Hand({
    subsets: ["latin"],
    variable: "--font-handwriting",
    weight: ["400"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en" className={"scroll-smooth min-h-0 h-full"}>
            <body
                className={clsx(
                    "bg-background text-primary h-full",
                    InterFont.variable, JustAnotherHandFont.variable
                )}
                style={dottedBackground("rgba(255, 255, 255, 0.02)", "2px", "25px")}
            >
                <RemoveAnimateAppear />
                <noscript>
                    <style>
                        {`
                            [data-animate-appear] {
                                opacity: 1 !important;
                            }
                        `}
                    </style>
                </noscript>
                {children}
            </body>
        </html>
    );
}
